os: linux
dist: focal
language: python
cache: pip

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"
  - "nightly"

install:
  - pip install -r requirements-test.txt

script:
 - coverage run -m pytest
 - coverage report -m
 # - coverage html

after_success:
  - codecov
