site_name: sonyflake-py
docs_dir: docs/src
theme:
  name: material
  palette:
    scheme: slate
  features:
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  # custom_dir: docs/theme/

repo_url: https://github.com/hjpotter92/sonyflake-py
repo_name: hjpotter92/sonyflake-py

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Quick start: quickstart.md
  - Reference: reference.md
  - Coverage report: https://app.codecov.io/gh/hjpotter92/sonyflake-py
  - Changelog: changelog.md

plugins:
  - search:
      separator: '[-.\s]+'
  - mkdocstrings
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_empty_space: true
        remove_comments: true
        reduce_boolean_attributes: true
  - git-revision-date

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
