site_name: sonyflake-py
docs_dir: docs/src
theme:
  name: material
  # custom_dir: docs/theme/

nav:
  - Home: index.md
  - Quick start: quickstart.md
  - Reference: reference.md
  - Coverage report: https://app.codecov.io/gh/hjpotter92/sonyflake-py
  - Changelog: changelog.md
  - GitHub: https://github.com/hjpotter92/sonyflake-py

plugins:
  - search
  - mkdocstrings
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_empty_space: true
        remove_comments: true
        reduce_boolean_attributes: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
