name: Lint check project

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Black Check
        uses: jpetrucciani/black-check@24.8.0
      - name: python-isort
        uses: isort/isort-action@v1
        with:
          isort-version: 5.13.2
          configuration: --profile black --diff --check-only
